image: node:16.14.0

pipelines:
  default:
      - step:
          name: Build
          script:
          - npm cache clean --force
          - rm -rf node_modules
          - npm install
          - CI=false npm run build
          artifacts: # defining build/ as an artifact
          - build/**
      - step:
          name: Deploy

            
          script:
            - pipe: atlassian/ftp-deploy:0.3.7
              variables:
                USER: $FTP_USERNAME
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: $FTP_SITE_ROOT_DIR
                LOCAL_PATH: 'build'
