import { Country } from "../country/CountryRes";
import { State } from "../state/userStateRes";
import { Nation } from "../Nation/userNationRes";
import { UserRole } from "../Role/userRoleRes";

export interface User  {
    id: string;
    registrationDate: string | null;
    userName: string;
    password: string;
    email: string;
    firstName: string;
    lastName: string;
    dateOfBirth: string | null;
    address: string;
    address2: string;
    city: string;
    countryID: string | null;
    country: Country;
    stateID: string | null;
    state: State;
    nationalityID: string | null;
    nationality: Nation;
    postalCode: string;
    phone: string;
    contactDetails: string;
    gender: string;
    hasPicture: number | null;
    profileDescription: string;
    otherInterests: string;
    otherLanguage: string;
    activationLink: string;
    resetPasswordLink: string;
    active: boolean;
    facebookId: string;
    facebookName: string;
    tweeterId: string;
    tweeterName: string;
    googleId: string;
    googleName: string;
    userRoleID: string | null;
    userRole: UserRole;
    hashPassword: string;
    percentComplete: number | null;
    vetted: boolean | null;
    activationDate: string | null;
    emailSent: number | null;
    points: number | null;
    referCode: string;
    referredBy: string;
    registerationChannel: string;
    recentLogin: string;
    lastLoginDate: string | null;
    profilePicture: string;
    lat: number | null;
    lon: number | null;
    emailSubscription: boolean | null;
    emailSubscriptionTypeInDays: string;
    emailSubscriptionEditDate: string | null;
}